name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Adjusted to a valid cron format for every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate snake.svg with your GitHub username
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: udukunda1 # Your GitHub username
          outputs: dist/snake.svg?palette=github-dark

      # Step 3: Push the generated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
